field: 47eeb68a-65d6-4d09-be70-f0037cfcf8fd # Content Blocks
fieldLayouts:
  dca70879-fbbf-4ebb-a17a-733a77b9c78f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21847131-85cd-4cd5-a00f-4c9589d30f1b # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 677ccc47-9183-4a96-8c17-ac4da6f407b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e44534a-45ac-46b9-a99b-f4a309b55247 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 202c5883-043c-41e5-b581-95e1618a94f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1271c2ad-f491-4b5f-ac84-15c97685f7f4
        userCondition: null
fields:
  1e44534a-45ac-46b9-a99b-f4a309b55247: # Caption
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  21847131-85cd-4cd5-a00f-4c9589d30f1b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d18b92a2-1d0e-4343-a37d-de5a5703835a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d18b92a2-1d0e-4343-a37d-de5a5703835a' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:d18b92a2-1d0e-4343-a37d-de5a5703835a' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: fullwidthImage
name: 'Full-width Image'
sortOrder: 6
