field: 47eeb68a-65d6-4d09-be70-f0037cfcf8fd # Content Blocks
fieldLayouts:
  8dc86aaf-74de-4003-882f-e64dad1f51e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2ab39786-79ea-4b1c-91b0-1489ca22792d # Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccf61587-54f5-4101-9a87-3405ec3142a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca424967-a482-4f31-b41c-d52395ab9dd8 # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29958b41-2e15-470c-bf5d-ac01e149a5c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d156ab9-41a4-491b-b781-049a63bfee00
        userCondition: null
fields:
  2ab39786-79ea-4b1c-91b0-1489ca22792d: # Display
    columnSuffix: wzqdkjlz
    contentColumnType: text
    fieldGroup: null
    handle: display
    instructions: null
    name: Display
    searchable: false
    settings:
      displayAsGraphic: null
      displayFullwidth: null
      options:
        -
          __assoc__:
            -
              - label
              - 'Inline player'
            -
              - showLabel
              - '1'
            -
              - value
              - inline
            -
              - imageUrl
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Image and lightbox'
            -
              - showLabel
              - '1'
            -
              - value
              - lightbox
            -
              - imageUrl
              - ''
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\buttonbox\fields\Buttons
  ca424967-a482-4f31-b41c-d52395ab9dd8: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: null
    name: Video
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:67c26d95-724f-4e48-a3a4-b19b1a624fa4' # Videos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d18b92a2-1d0e-4343-a37d-de5a5703835a' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select a video'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:67c26d95-724f-4e48-a3a4-b19b1a624fa4' # Videos
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: video
name: 'Video Embed'
sortOrder: 9
