fieldLayouts:
  717437c6-dfc1-4c72-aff1-1255fde1b3a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f89ef0de-17fa-4a29-9551-7762769a42c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 440ee12e-8957-4daa-bac9-420f461a30c6 # Feature Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12704da1-3c01-4c81-83b1-ede601deef45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e7a03ef-b278-47fe-8b04-570a23bd1b8d # Summary
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd153eb6-3cba-4ea5-af7d-66bafd8007fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47eeb68a-65d6-4d09-be70-f0037cfcf8fd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65e4bd10-6059-4742-aa9f-f4a5ef0136e2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ad4811f-f26b-4ad5-9db7-be6fe1a27cbd
        userCondition: null
handle: childListing
hasTitleField: true
name: 'Listing – Children'
section: 59180e18-27bd-4cb4-9fc7-39eeea9c19b0 # Sitemap
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
