fieldLayouts:
  127c58ed-eb75-42e2-91f8-e84c10e409d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe2fd6dd-6fb0-457a-bead-39ff73d8febc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 440ee12e-8957-4daa-bac9-420f461a30c6 # Feature Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f29f9c51-b955-4605-836c-ddb09a2fe269
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e7a03ef-b278-47fe-8b04-570a23bd1b8d # Summary
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7361244-017e-4653-b82f-4dac6350fecf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47eeb68a-65d6-4d09-be70-f0037cfcf8fd # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e4eb57c-cb0f-4a7e-86bf-20f2cb290df0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d4702eb3-c9f2-4577-9dd4-3169599781fc
        userCondition: null
handle: contentPage
hasTitleField: true
name: 'Content Page'
section: 59180e18-27bd-4cb4-9fc7-39eeea9c19b0 # Sitemap
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
