fieldLayouts:
  c2e8dc34-f64b-4f83-85e9-e095ac0ba2ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34085651-d758-4e6b-9555-974b2ca355c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 440ee12e-8957-4daa-bac9-420f461a30c6 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 828225f5-4f45-4827-a582-5830bae39bb8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 017e139f-d668-46f3-8782-6725bad0ac49
        userCondition: null
handle: search
hasTitleField: false
name: Search
section: e3ac717d-d2ef-4306-8fec-eaf749d79da2 # Search
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
