fieldLayouts:
  dccd83ab-ba3d-482d-b06e-fd3a995366e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 904906e6-81cf-4584-8b53-8766a78f0ad4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 87c32f4e-e24f-4b86-a919-1e4cfd906fc2
        userCondition: null
fs: downloads
handle: downloads
name: Downloads
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
