fieldLayouts:
  ecb426d1-7c4b-4d34-9f73-da1b65f10c5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a0674707-0bdb-4caa-8785-360fb1d768f9
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'This should describe the appearance and function of an image. Screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can''t be loaded for some reason.'
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: ebf1a506-9813-4a24-923e-e9a1edcbaee3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7b4e367-cbcf-4718-a238-ccd85b0179fb # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 461c1a04-cd18-4b30-bb8a-86087fad19c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f97891de-309b-47a6-ad6d-8b47cacc4fb4
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
