fieldLayouts:
  2af83ee2-a38d-4d90-8311-cb0911506567:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c3762d9e-359d-4de7-898f-1cf5d8a62c4c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4eddd16-8bb8-4d7c-8639-bf445c437c78
        userCondition: null
fs: userPhotos
handle: userPhotos
name: 'User Photos'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
