fieldLayouts:
  a5071195-34af-4b07-b6cf-9b3922ad9fa3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a81cc58b-35e2-40d2-b800-8333f02c8d1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55938729-d99e-49e4-88ea-1b0a4bf8c246
        userCondition: null
fs: videos
handle: videos
name: Videos
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
