columnSuffix: null
contentColumnType: string
fieldGroup: 2b4f9b34-11e8-4190-b278-9d86c1903e13 # Content
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
