columnSuffix: null
contentColumnType: text
fieldGroup: 76eb371f-fb30-4a2c-8e62-eb9cd1629262 # Globals
handle: linkedinPage
instructions: 'The slug for your LinkedIn Page, without https://linkedin.com/company/.'
name: 'LinkedIn Page'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: example-company-name
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
