columnSuffix: null
contentColumnType: string
fieldGroup: 559aaca6-8c69-45a0-9e04-d3d1ac89abb6 # News
handle: newsCategory
instructions: null
name: Category
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:1174bde9-64cb-4130-8e97-e4310f7c7285' # News Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
