columnSuffix: null
contentColumnType: text
fieldGroup: 8295a178-63b9-4be8-b53c-bc1e7e37bec1 # SEO
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogType
    - ogTitle
    - ogSiteNamePosition
    - ogDescription
    - ogImage
    - ogImageDescription
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - siteNamePosition
    - seoDescription
    - seoKeywords
    - seoImage
    - seoImageDescription
    - robots
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - twitterTitle
    - twitterSiteNamePosition
    - twitterDescription
    - twitterImage
    - twitterImageDescription
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
