defaultPlacement: end
enableVersioning: true
handle: search
name: Search
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7cff4d8a-4325-4cf7-955c-d5de168e98e5: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: search
    uriFormat: search
type: single
