handle: customTemplate
name: 'Custom Template'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: false
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: 99
template: null
useCustomTemplates: false
